apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.15.0/controller.yaml
- secret.yaml