apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: app-b-cm
  literals:
  - SERVICE_NAME=app-b
secretGenerator:
- name: app-b-secret
  literals:
  - SECRET_VALUE=secret
images:
- name: nginx
  newTag: 1.19.10

