apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-b
  serviceName: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: nginx
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-b-cm
        - secretRef:
            name: app-b-secret
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: nginx-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi