apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: nginx:1.19.10
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-a-cm