apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-e
  template:
    metadata:
      labels:
        app: app-e
    spec:
      containers:
      - name: app-e
        image: nginx:1.19.10
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-e-cm