apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install.yaml
patchesJson6902:
- path: patch-service.yaml
  target:
    kind: Service
    name: argocd-server
    version: v1